# Lab Assignment Three: Extending Logistic Regression

### Authors
- Juliana Antonio
- Xiaona Hang
- Chuanqi Deng

### 1. Preparation and Overview

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

raw_data = pd.read_csv("data/bodyPerformance.csv")

data = pd.get_dummies(raw_data, columns=['gender'],dtype=np.int8) # one-hot encoding for gender
labels = data['class'].map(lambda c: ord(c) - ord('A')) # encode lables into integer
data.drop(['class'], axis=1, inplace=True) # remove class column

# scale
scaler = StandardScaler()
features = scaler.fit_transform(data)

# split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.8)
print(features.shape, X_train.shape, X_test.shape,  y_train.shape, y_test.shape)

# 5-fold cross-validation
cross_validator = KFold(n_splits=5)
split_indices = list(cross_validator.split(features, labels))

# example code
# for train_indices, test_indices in split_indices:
#     X_train, y_train = features[train_indices], labels[train_indices]
#     X_test, y_test = features[test_indices], labels[test_indices]
#     print(features.shape, X_train.shape, X_test.shape,  y_train.shape, y_test.shape)
#     # training...

(13393, 12) (10714, 12) (2679, 12) (10714,) (2679,)

In [2]:
raw_data

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27.0,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25.0,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31.0,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32.0,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28.0,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25.0,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21.0,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39.0,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64.0,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34.0,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [5]:
data

,age,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,gender_F,gender_M
0,27.0,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,0,1
1,25.0,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,0,1
2,31.0,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,0,1
3,32.0,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,0,1
4,28.0,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25.0,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,0,1
13389,21.0,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,0,1
13390,39.0,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,0,1
13391,64.0,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,1,0
13392,34.0,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,0,1

In [4]:
features

array([[-0.71743212,  0.44387298,  0.65215002, ...,  0.67400862,
        -0.76275036,  0.76275036],
       [-0.8642197 , -0.42246548, -0.97473438, ...,  0.97501314,
        -0.76275036,  0.76275036],
       [-0.42385695,  1.31021144,  0.88312744, ..., -0.22900492,
        -0.76275036,  0.76275036],
       ...,
       [ 0.16329338,  1.02538783,  1.09234611, ...,  0.97501314,
        -0.76275036,  0.76275036],
       [ 1.99813815, -2.66545136, -0.81572819, ..., -2.88787813,
         1.31104493, -1.31104493],
       [-0.20367558, -0.54114198, -0.11275345, ..., -0.25408863,
        -0.76275036,  0.76275036]])

References: